CREATE TABLE roadmap_nodes (
    node_id INT PRIMARY KEY,
    phase INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    topic VARCHAR(50) NOT NULL,
    keyword VARCHAR(50) NOT NULL,
    difficulty VARCHAR(20) NOT NULL,
    problem_id BIGINT NULL,
    FOREIGN KEY (problem_id) REFERENCES problems(id) ON DELETE SET NULL
);

INSERT INTO roadmap_nodes (node_id, phase, title, topic, keyword, difficulty, problem_id) VALUES
(1, 1, 'Tìm phần tử cực đại', 'Array', 'Shopee', 'EASY', NULL),
(2, 1, 'Đảo ngược chuỗi ký tự', 'String', 'TikTok', 'EASY', NULL),
(3, 1, 'Kiểm tra chuỗi đối xứng', 'String', 'Facebook', 'EASY', NULL),
(4, 1, 'Loại bỏ phần tử trùng lặp', 'Array', 'Lazada', 'EASY', NULL),
(5, 1, 'Dịch chuyển các số 0 về cuối', 'Array', 'Grab', 'EASY', NULL),
(6, 1, 'Tìm cặp số có tổng bằng T', 'Array', 'Shopee', 'MEDIUM', NULL),
(7, 1, 'Nén chuỗi ký tự trùng lặp', 'String', 'Netflix', 'MEDIUM', NULL),
(8, 1, 'Tìm kiếm chuỗi con', 'String', 'Google', 'MEDIUM', NULL),
(9, 1, 'Xoay vòng mảng xoay chiều', 'Array', 'Spotify', 'MEDIUM', NULL),
(10, 1, 'Nhân hai ma trận', 'Array', 'Tesla', 'HARD', NULL),
(11, 2, 'Hợp nhất hai mảng đã sắp xếp', 'Two Pointers', 'Grab', 'EASY', NULL),
(12, 2, 'Kiểm tra chuỗi con viết xen kẽ', 'Two Pointers', 'Shopee', 'EASY', NULL),
(13, 2, 'Loại bỏ phần tử trùng lặp trong mảng đã sort', 'Two Pointers', 'Tiki', 'EASY', NULL),
(14, 2, 'Tìm cặp phần tử gần đích nhất', 'Two Pointers', 'MoMo', 'MEDIUM', NULL),
(15, 2, 'Tính toán lượng nước mưa giữ được', 'Two Pointers', 'Shopee', 'MEDIUM', NULL),
(16, 2, 'Tìm 3 số có tổng bằng 0', 'Two Pointers', 'TikTok', 'MEDIUM', NULL),
(17, 2, 'Phân loại các màu sắc/loại phần tử', 'Two Pointers', 'Binance', 'MEDIUM', NULL),
(18, 2, 'Chứa nhiều nước nhất', 'Two Pointers', 'Grab', 'HARD', NULL),
(19, 3, 'Tổng lớn nhất của mảng con kích thước K', 'Sliding Window', 'Netflix', 'EASY', NULL),
(20, 3, 'Chuỗi con ngắn nhất chứa ký tự lặp', 'Sliding Window', 'Spotify', 'EASY', NULL),
(21, 3, 'Trung bình cộng mảng con', 'Sliding Window', 'Shopee', 'EASY', NULL),
(22, 3, 'Chuỗi con dài nhất không có ký tự lặp', 'Sliding Window', 'TikTok', 'MEDIUM', NULL),
(23, 3, 'Đếm số ký tự anagram con', 'Sliding Window', 'Google', 'MEDIUM', NULL),
(24, 3, 'Mảng con có tổng lớn hơn hoặc bằng S', 'Sliding Window', 'Lazada', 'MEDIUM', NULL),
(25, 3, 'Thay thế ký tự để được chuỗi liên tục', 'Sliding Window', 'Facebook', 'MEDIUM', NULL),
(26, 3, 'Chuỗi con ngắn nhất chứa đủ ký tự mẫu', 'Sliding Window', 'Shopee', 'HARD', NULL),
(27, 4, 'Kiểm tra xem hai từ có đảo chữ', 'HashMap', 'Shopee', 'EASY', NULL),
(28, 4, 'Tìm số xuất hiện duy nhất một lần', 'HashSet', 'Grab', 'EASY', NULL),
(29, 4, 'Kiểm tra sự trùng lặp trong khoảng K', 'HashSet', 'Spotify', 'EASY', NULL),
(30, 4, 'Tìm hai số có tổng bằng K', 'HashMap', 'MoMo', 'EASY', NULL),
(31, 4, 'Đếm tần suất các từ trong văn bản', 'HashMap', 'Google', 'MEDIUM', NULL),
(32, 4, 'Nhóm các chuỗi đảo chữ lại với nhau', 'HashMap', 'Shopee', 'MEDIUM', NULL),
(33, 4, 'Chuỗi con dài nhất chứa các phần tử liên tiếp', 'HashSet', 'TikTok', 'MEDIUM', NULL),
(34, 4, 'Thiết kế bộ đệm LRU Cache', 'HashMap', 'Netflix', 'HARD', NULL),
(35, 4, 'Tìm tất cả các chuỗi con trùng lặp', 'HashMap', 'YouTube', 'MEDIUM', NULL),
(36, 4, 'Hệ thống xếp hạng người dùng', 'HashMap', 'Steam', 'HARD', NULL),
(37, 5, 'Kiểm tra dấu ngoặc hợp lệ', 'Stack', 'Shopee', 'EASY', NULL),
(38, 5, 'Thiết kế Ngăn xếp hỗ trợ lấy Min nhanh', 'Stack', 'Grab', 'EASY', NULL),
(39, 5, 'Hàng đợi mô phỏng bằng hai Ngăn xếp', 'Queue', 'TikTok', 'EASY', NULL),
(40, 5, 'Xóa bỏ các ký tự trùng lặp kề nhau', 'Stack', 'Lazada', 'EASY', NULL),
(41, 5, 'Đánh giá biểu thức Ba Lan ngược', 'Stack', 'Google', 'MEDIUM', NULL),
(42, 5, 'Tìm ngày ấm áp tiếp theo', 'Stack', 'NASA', 'MEDIUM', NULL),
(43, 5, 'Đơn giản hóa đường dẫn thư mục', 'Stack', 'Apple', 'MEDIUM', NULL),
(44, 5, 'Thiết kế bộ giải mã chuỗi lặp', 'Stack', 'TikTok', 'MEDIUM', NULL),
(45, 5, 'Phần tử lớn nhất trong cửa sổ trượt', 'PriorityQueue', 'Grab', 'HARD', NULL),
(46, 5, 'Chiều cao của các tòa nhà nhìn thấy', 'Stack', 'Spotify', 'HARD', NULL),
(47, 6, 'Tìm kiếm nhị phân cơ bản', 'Binary Search', 'Shopee', 'EASY', NULL),
(48, 6, 'Tìm vị trí chèn phần tử', 'Binary Search', 'Google', 'EASY', NULL),
(49, 6, 'Tìm phần tử đầu tiên và cuối cùng', 'Binary Search', 'TikTok', 'MEDIUM', NULL),
(50, 6, 'Tìm kiếm trong mảng đã xoay vòng', 'Binary Search', 'Grab', 'MEDIUM', NULL),
(51, 6, 'Tìm đỉnh của mảng ngọn núi', 'Binary Search', 'NASA', 'MEDIUM', NULL),
(52, 6, 'Tìm giá trị căn bậc hai số nguyên', 'Binary Search', 'Tesla', 'EASY', NULL),
(53, 6, 'Chia kẹo cho trẻ em tối ưu', 'Binary Search', 'Shopee', 'MEDIUM', NULL),
(54, 6, 'Tìm phần tử nhỏ nhất trong mảng xoay vòng', 'Binary Search', 'Grab', 'MEDIUM', NULL),
(55, 6, 'Tìm khoảng cách nhỏ nhất giữa K máy chủ', 'Binary Search', 'Binance', 'HARD', NULL),
(56, 7, 'Duyệt cây nhị phân theo mức', 'Graph & Tree', 'Google', 'EASY', NULL),
(57, 7, 'Tìm chiều sâu tối đa của cây nhị phân', 'Graph & Tree', 'Apple', 'EASY', NULL),
(58, 7, 'Kiểm tra hai cây nhị phân giống nhau', 'Graph & Tree', 'Facebook', 'EASY', NULL),
(59, 7, 'Tìm kiếm trên đồ thị BFS', 'Graph & Tree', 'Grab', 'MEDIUM', NULL),
(60, 7, 'Tìm số lượng đảo nước liên kết', 'Graph & Tree', 'Shopee', 'MEDIUM', NULL),
(61, 7, 'Kiểm tra đồ thị có chu trình', 'Graph & Tree', 'TikTok', 'MEDIUM', NULL),
(62, 7, 'Tìm đường đi ngắn nhất trên mê cung', 'Graph & Tree', 'Grab', 'MEDIUM', NULL),
(63, 7, 'Lịch trình học các môn học', 'Graph & Tree', 'Google', 'MEDIUM', NULL),
(64, 7, 'Khôi phục cây nhị phân từ tiền thứ tự', 'Graph & Tree', 'Spotify', 'HARD', NULL),
(65, 7, 'Tìm cầu trong đồ thị kết nối', 'Graph & Tree', 'Facebook', 'HARD', NULL),
(66, 8, 'Tìm số Fibonacci bằng DP', 'Dynamic Programming', 'Shopee', 'EASY', NULL),
(67, 8, 'Đi lên cầu thang (Climbing Stairs)', 'Dynamic Programming', 'Shopee', 'EASY', NULL),
(68, 8, 'Kẻ trộm chuyên nghiệp (House Robber)', 'Dynamic Programming', 'Grab', 'MEDIUM', NULL),
(69, 8, 'Tìm số cách đổi tiền xu (Coin Change)', 'Dynamic Programming', 'Binance', 'MEDIUM', NULL),
(70, 8, 'Chuỗi con tăng dài nhất (LIS)', 'Dynamic Programming', 'Google', 'MEDIUM', NULL),
(71, 8, 'Chuỗi con chung dài nhất (LCS)', 'Dynamic Programming', 'Spotify', 'MEDIUM', NULL),
(72, 8, 'Bài toán cái túi (Knapsack 0/1)', 'Dynamic Programming', 'TikTok', 'HARD', NULL),
(73, 8, 'Tìm khoảng cách sửa đổi ngắn nhất (Edit Distance)', 'Dynamic Programming', 'Microsoft', 'HARD', NULL),
(74, 8, 'Tìm đường đi có tổng nhỏ nhất trên tam giác', 'Dynamic Programming', 'Apple', 'MEDIUM', NULL),
(75, 8, 'Giải mã chuỗi số (Decode Ways)', 'Dynamic Programming', 'Netflix', 'HARD', NULL);
